import { useState } from "react";
import { X, FileText, Printer } from "lucide-react";
import { jsPDF } from "jspdf";
import type { QRData } from "./types";

interface Props {
  open: boolean;
  onClose: () => void;
  qrData: QRData;
  onSuccess: (msg: string) => void;
  onError: (msg: string) => void;
}

const ExportQRModal = ({ open, onClose, qrData, onSuccess, onError }: Props) => {
  const [exporting, setExporting] = useState(false);

  if (!open) return null;

  const handlePDF = async () => {
    setExporting(true);
    try {
      const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
      const pageW = doc.internal.pageSize.getWidth();

      // White background
      doc.setFillColor(255, 255, 255);
      doc.rect(0, 0, pageW, doc.internal.pageSize.getHeight(), "F");

      let y = 30;

      // Title
      if (qrData.label) {
        doc.setFontSize(18);
        doc.setTextColor(30, 30, 46);
        doc.text(qrData.label, pageW / 2, y, { align: "center" });
        y += 12;
      }

      // QR Code - centered, large
      const qrSize = 80;
      doc.addImage(qrData.qrDataUrl, "PNG", (pageW - qrSize) / 2, y, qrSize, qrSize);
      y += qrSize + 12;

      // Payee Name
      if (qrData.name) {
        doc.setFontSize(16);
        doc.setTextColor(30, 30, 46);
        doc.text(qrData.name, pageW / 2, y, { align: "center" });
        y += 8;
      }

      // UPI ID
      doc.setFontSize(11);
      doc.setTextColor(120, 120, 120);
      doc.text(qrData.upiId, pageW / 2, y, { align: "center" });
      y += 8;

      // Amount
      if (qrData.amount) {
        doc.setFontSize(22);
        doc.setTextColor(37, 99, 235);
        doc.text(`₹${Number(qrData.amount).toLocaleString("en-IN")}`, pageW / 2, y, { align: "center" });
        y += 10;
      }

      // Note
      if (qrData.note) {
        doc.setFontSize(10);
        doc.setTextColor(120, 120, 120);
        doc.text(qrData.note, pageW / 2, y, { align: "center" });
        y += 8;
      }

      // Footer
      doc.setFontSize(8);
      doc.setTextColor(180, 180, 180);
      doc.text("Generated by Open UPI QR Generator", pageW / 2, y + 10, { align: "center" });

      doc.save("upi-payment-qr.pdf");
      onSuccess("PDF downloaded successfully!");
      onClose();
    } catch {
      onError("Failed to generate PDF");
    } finally {
      setExporting(false);
    }
  };

  const handlePrint = () => {
    const printWindow = window.open("", "_blank", "width=800,height=600");
    if (!printWindow) {
      onError("Pop-up blocked. Please allow pop-ups to print.");
      return;
    }

    const amountHtml = qrData.amount
      ? `<p style="font-size:28px;font-weight:800;color:#2563eb;margin:8px 0">₹${Number(qrData.amount).toLocaleString("en-IN")}</p>`
      : "";
    const noteHtml = qrData.note ? `<p style="font-size:12px;color:#888;margin:4px 0">${qrData.note}</p>` : "";
    const labelHtml = qrData.label ? `<h2 style="font-size:20px;font-weight:700;color:#1a1a2e;margin-bottom:16px">${qrData.label}</h2>` : "";
    const nameHtml = qrData.name ? `<p style="font-size:18px;font-weight:700;color:#1a1a2e;margin:4px 0">${qrData.name}</p>` : "";

    printWindow.document.write(`<!DOCTYPE html><html><head><title>UPI QR Code</title><style>
      body{margin:0;padding:40px;display:flex;justify-content:center;align-items:center;min-height:100vh;background:#fff;font-family:system-ui,-apple-system,sans-serif}
      .card{text-align:center;max-width:400px}
      img{width:280px;height:280px;margin:16px 0}
      @media print{body{padding:20mm}}
    </style></head><body><div class="card">
      ${labelHtml}
      <img src="${qrData.qrDataUrl}" alt="UPI QR Code"/>
      ${nameHtml}
      <p style="font-size:13px;color:#888">${qrData.upiId}</p>
      ${amountHtml}${noteHtml}
      <p style="font-size:9px;color:#ccc;margin-top:20px">Generated by Open UPI QR Generator</p>
    </div></body></html>`);

    printWindow.document.close();
    printWindow.focus();
    setTimeout(() => {
      printWindow.print();
      printWindow.close();
    }, 400);

    onSuccess("Print dialog opened!");
    onClose();
  };

  return (
    <div
      className="fixed inset-0 z-[200] flex items-center justify-center p-4 animate-fade-in"
      onClick={(e) => { if (e.target === e.currentTarget) onClose(); }}
    >
      <div className="absolute inset-0 bg-black/50" />
      <div className="relative bg-card border border-border rounded-2xl shadow-xl w-full max-w-xs p-6 space-y-4 animate-scale-in">
        <div className="flex items-center justify-between">
          <h3 className="text-base font-bold text-foreground">Export QR</h3>
          <button onClick={onClose} className="p-1.5 rounded-xl hover:bg-muted transition-colors text-muted-foreground">
            <X className="w-4 h-4" />
          </button>
        </div>

        <button
          onClick={handlePDF}
          disabled={exporting}
          className="w-full flex items-center gap-3 p-3.5 rounded-xl border border-border hover:bg-muted transition-all text-left disabled:opacity-50"
        >
          <FileText className="w-5 h-5 text-primary flex-shrink-0" />
          <div>
            <p className="text-sm font-semibold text-foreground">Download as PDF</p>
            <p className="text-[11px] text-muted-foreground">High-res QR with payment details</p>
          </div>
        </button>

        <button
          onClick={handlePrint}
          className="w-full flex items-center gap-3 p-3.5 rounded-xl border border-border hover:bg-muted transition-all text-left"
        >
          <Printer className="w-5 h-5 text-primary flex-shrink-0" />
          <div>
            <p className="text-sm font-semibold text-foreground">Print QR</p>
            <p className="text-[11px] text-muted-foreground">Print-friendly A4 layout</p>
          </div>
        </button>
      </div>
    </div>
  );
};

export default ExportQRModal;
