/**
 * Branding constants and helpers.
 *
 * Free users always have branding ON. A future Pro tier may remove it.
 * Currently fully simulated in the frontend — no backend, no auth.
 */

// Single-line, plain ASCII branding. No newlines, no special symbols —
// many UPI apps reject %0A or unusual punctuation inside `tn`.
export const BRANDING_NOTE =
  " - This QR Code Generated by upiqrgenerator.lovable.app build by CHARAN RAJ TECHY";

export const BRANDING_NOTE_STANDALONE =
  "This QR Code Generated by upiqrgenerator.lovable.app build by CHARAN RAJ TECHY";

export const BRANDING_PREVIEW_TEXT =
  "Generated by upiqrgenerator.lovable.app";

export const NOTE_MAX_LENGTH = 100;

/**
 * Future-ready Pro flag. Replace this with real auth-driven logic later.
 * When `true`, users may toggle branding off; when `false`, branding is forced on.
 */
export const isProUser = false;

/**
 * Compose the final QR note string. Appends branding unless the caller is
 * an authenticated Pro user who has explicitly removed branding.
 *
 * - Empty note  -> standalone branding line
 * - Has note    -> "<note>\n<branding>"
 * - Prevents duplicate branding insertion
 */
export function composeBrandedNote(userNote: string, removeBranding: boolean): string {
  const note = (userNote || "").trim();
  const allowRemoval = isProUser && removeBranding;

  if (allowRemoval) return note;

  // Prevent duplicates
  if (note.includes(BRANDING_NOTE) || note.includes(BRANDING_NOTE_STANDALONE)) {
    return note;
  }

  if (!note) return BRANDING_NOTE_STANDALONE;
  // Single-line join — never insert newline characters into tn.
  return `${note}${BRANDING_NOTE}`;
}
